# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

Uninstall-BinFile "androidvideo"
Uninstall-BinFile "cutvideo"
Uninstall-BinFile "removeaudio"
Uninstall-BinFile "rotatevideo"
Uninstall-BinFile "split"
Uninstall-BinFile "videotomp3"
Uninstall-BinFile "ytandroid"
Uninstall-BinFile "ytvideo"
