# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

$ErrorActionPreference = 'Stop';
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

Install-BinFile -Name 'androidvideo' -Path (Join-Path (Join-Path $toolsDir 'bin') 'androidvideo.bat')
Install-BinFile -Name 'cutvideo' -Path (Join-Path (Join-Path $toolsDir 'bin') 'cutvideo.bat')
Install-BinFile -Name 'removeaudio' -Path (Join-Path (Join-Path $toolsDir 'bin') 'removeaudio.bat')
Install-BinFile -Name 'rotatevideo' -Path (Join-Path (Join-Path $toolsDir 'bin') 'rotatevideo.bat')
Install-BinFile -Name 'split' -Path (Join-Path (Join-Path $toolsDir 'bin') 'split.bat')
Install-BinFile -Name 'videotomp3' -Path (Join-Path (Join-Path $toolsDir 'bin') 'videotomp3.bat')
Install-BinFile -Name 'ytandroid' -Path (Join-Path (Join-Path $toolsDir 'bin') 'ytandroid.bat')
Install-BinFile -Name 'ytvideo' -Path (Join-Path (Join-Path $toolsDir 'bin') 'ytvideo.bat')
